"""add_signers_to_deal

Revision ID: 64b521e13418
Revises: payreq_handshake01
Create Date: 2026-04-26 14:07:12.401933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64b521e13418'
down_revision: Union[str, None] = 'payreq_handshake01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('signers', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Фиксированные адреса подписантов {sender, receiver, arbiter} на момент создания эскроу (не меняются при смене primary address в DID)'))
    op.alter_column('deal', 'sender_did',
               existing_type=sa.VARCHAR(length=255),
               comment='Sender DID (space identifier, primary address may change)',
               existing_comment='Sender DID (owner of the deal)',
               existing_nullable=False)
    op.alter_column('deal', 'receiver_did',
               existing_type=sa.VARCHAR(length=255),
               comment='Receiver DID (space identifier, primary address may change)',
               existing_comment='Receiver DID',
               existing_nullable=False)
    op.alter_column('deal', 'arbiter_did',
               existing_type=sa.VARCHAR(length=255),
               comment='Arbiter DID (space identifier, primary address may change)',
               existing_comment='Arbiter DID',
               existing_nullable=False)
    op.create_index('ix_deal_signers', 'deal', ['signers'], unique=False, postgresql_using='gin')
    op.alter_column('exchange_services', 'space',
               existing_type=sa.VARCHAR(length=255),
               comment='Идентификатор space (как в URL /{space}/…)',
               existing_nullable=False)
    op.alter_column('exchange_services', 'space_wallet_id',
               existing_type=sa.INTEGER(),
               comment='Корпоративный кошелёк спейса (реквизиты offRamp); NULL для on_ramp',
               existing_comment='Корпоративный кошелёк спейса (wallets.id); обязателен для off_ramp',
               existing_nullable=True)
    op.alter_column('exchange_services', 'description',
               existing_type=sa.TEXT(),
               comment='Описание направления для UI',
               existing_nullable=True)
    op.alter_column('exchange_services', 'payment_code',
               existing_type=sa.VARCHAR(length=128),
               comment='Код платёжного метода (bc.yaml); форма из резолвера если requisites_form_schema пуст',
               existing_nullable=True)
    op.create_index(op.f('ix_exchange_services_payment_code'), 'exchange_services', ['payment_code'], unique=False)
    op.create_index(op.f('ix_exchange_services_space'), 'exchange_services', ['space'], unique=False)
    op.alter_column('guarantor_directions', 'payment_code',
               existing_type=sa.VARCHAR(length=128),
               comment='Код платёжного метода (payment_code в bc.yaml). Зарезервировано: «*» — все способы оплаты для данной валюты; с конкретными методами по той же валюте в одном space не сочетается (проверка в GuarantorService).',
               existing_comment='Код платёжного метода (payment_code в bc.yaml)',
               existing_nullable=False)
    op.create_index(op.f('ix_guarantor_directions_id'), 'guarantor_directions', ['id'], unique=False)
    op.alter_column('guarantor_profiles', 'arbiter_public_slug',
               existing_type=sa.VARCHAR(length=64),
               comment='Уникальный сегмент URL /arbiter/{slug} вместо DID арбитра',
               existing_comment='Уникальный сегмент URL /arbiter/{slug} вместо DID',
               existing_nullable=True)
    op.create_index(op.f('ix_guarantor_profiles_id'), 'guarantor_profiles', ['id'], unique=False)
    op.alter_column('orders', 'id',
               existing_type=sa.BIGINT(),
               comment='Идентификатор ордера',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('orders', 'dedupe_key',
               existing_type=sa.VARCHAR(length=255),
               comment='Стабильный ключ для идемпотентного refresh',
               existing_comment='Стабильный ключ для upsert refresh',
               existing_nullable=False)
    op.alter_column('orders', 'space_wallet_id',
               existing_type=sa.INTEGER(),
               comment='Ramp-кошелёк спейса; связь с space через wallets.owner_did',
               existing_comment='Ramp-кошелёк спейса (связь с owner через wallets.owner_did)',
               existing_nullable=True)
    op.alter_column('orders', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='kind, wallet_id (дубль id для UI), diff, multisig_setup_status, адреса',
               existing_comment='kind, diff, статусы multisig, адреса — гибко через JSON',
               existing_nullable=True)
    op.alter_column('payment_request', 'public_ref',
               existing_type=sa.VARCHAR(length=10),
               comment='Короткий публичный код заявки (ссылки, resolve)',
               existing_comment='Короткий публичный код заявки (список/ссылки)',
               existing_nullable=False)
    op.alter_column('payment_request', 'space_id',
               existing_type=sa.INTEGER(),
               comment='Primary space (WalletUser row)',
               existing_nullable=False)
    op.alter_column('payment_request', 'arbiter_did',
               existing_type=sa.VARCHAR(length=255),
               comment='DID арбитра (контекст Simple из path arbiter_space_did)',
               existing_nullable=False)
    op.alter_column('payment_request', 'heading',
               existing_type=sa.VARCHAR(length=256),
               comment='Пользовательский заголовок (опционально)',
               existing_comment='Пользовательский заголовок заявки',
               existing_nullable=True)
    op.alter_column('payment_request', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Срок действия заявки; NULL — без ограничения по времени',
               existing_comment='Срок действия; NULL — без ограничения',
               existing_nullable=True)
    op.alter_column('payment_request', 'deactivated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Деактивация владельцем; NULL — заявка активна в списке',
               existing_comment='Деактивация пользователем; NULL — активна',
               existing_nullable=True)
    op.drop_index('ix_payment_request_commissioners_gin', table_name='payment_request', postgresql_using='gin')
    op.drop_index('uq_payment_request_public_ref', table_name='payment_request')
    op.drop_constraint('uq_payment_request_uid', 'payment_request', type_='unique')
    op.create_index(op.f('ix_payment_request_pk'), 'payment_request', ['pk'], unique=False)
    op.create_index(op.f('ix_payment_request_public_ref'), 'payment_request', ['public_ref'], unique=True)
    op.create_index(op.f('ix_payment_request_uid'), 'payment_request', ['uid'], unique=True)
    op.drop_constraint('primary_wallets_wallet_user_id_key', 'primary_wallets', type_='unique')
    op.drop_index('ix_primary_wallets_wallet_user_id', table_name='primary_wallets')
    op.create_index(op.f('ix_primary_wallets_wallet_user_id'), 'primary_wallets', ['wallet_user_id'], unique=True)
    op.create_index(op.f('ix_space_payment_form_overrides_id'), 'space_payment_form_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_space_payment_form_overrides_space'), 'space_payment_form_overrides', ['space'], unique=False)
    op.alter_column('token_balance_cache', 'id',
               existing_type=sa.BIGINT(),
               comment='Autoincrement primary key',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('token_balance_cache', 'address',
               existing_type=sa.VARCHAR(length=255),
               comment='Wallet address in native encoding for the chain (e.g. TRON base58)',
               existing_nullable=False)
    op.alter_column('token_balance_cache', 'blockchain',
               existing_type=sa.VARCHAR(length=50),
               comment='Chain identifier (e.g. TRON, ETH)',
               existing_nullable=False)
    op.alter_column('token_balance_cache', 'contract_address',
               existing_type=sa.VARCHAR(length=255),
               comment='Token contract address in native encoding for the chain',
               existing_nullable=False)
    op.alter_column('token_balance_cache', 'balance_raw',
               existing_type=sa.NUMERIC(precision=78, scale=0),
               comment='Token balance in base-units/raw uint256',
               existing_nullable=False)
    op.alter_column('token_balance_cache', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Time of last update (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_token_balance_cache_blockchain'), 'token_balance_cache', ['blockchain'], unique=False)
    op.create_index(op.f('ix_token_balance_cache_id'), 'token_balance_cache', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_space_ui_prefs_id'), 'wallet_space_ui_prefs', ['id'], unique=False)
    op.alter_column('wallet_users', 'profile',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Space profile: description, company_name, icon (base64), optional language (ru|en)',
               existing_comment='Space profile: description, icon (base64)',
               existing_nullable=True)
    op.alter_column('wallets', 'tron_address',
               existing_type=sa.VARCHAR(length=34),
               comment='TRON address (optional for external Ethereum-only requisites)',
               existing_comment='TRON address',
               existing_nullable=True)
    op.alter_column('wallets', 'ethereum_address',
               existing_type=sa.VARCHAR(length=42),
               comment='Ethereum address (optional for external TRC20-only requisites)',
               existing_comment='Ethereum address',
               existing_nullable=True)
    op.alter_column('wallets', 'multisig_setup_status',
               existing_type=sa.VARCHAR(length=32),
               comment='pending_config|awaiting_funding|ready_for_permissions|permissions_submitted|active|failed|reconfigure; NULL=legacy active',
               existing_comment='Multisig setup lifecycle; NULL = legacy wallet = active',
               existing_nullable=True)
    op.alter_column('wallets', 'multisig_setup_meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='actors, owners (админы meta vs спейс), threshold_n/m, min_trx_sun, last_trx_balance_sun, errors, tx ids',
               existing_comment='Multisig setup progress JSON (actors, thresholds, errors)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'multisig_setup_meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Multisig setup progress JSON (actors, thresholds, errors)',
               existing_comment='actors, owners (админы meta vs спейс), threshold_n/m, min_trx_sun, last_trx_balance_sun, errors, tx ids',
               existing_nullable=True)
    op.alter_column('wallets', 'multisig_setup_status',
               existing_type=sa.VARCHAR(length=32),
               comment='Multisig setup lifecycle; NULL = legacy wallet = active',
               existing_comment='pending_config|awaiting_funding|ready_for_permissions|permissions_submitted|active|failed|reconfigure; NULL=legacy active',
               existing_nullable=True)
    op.alter_column('wallets', 'ethereum_address',
               existing_type=sa.VARCHAR(length=42),
               comment='Ethereum address',
               existing_comment='Ethereum address (optional for external TRC20-only requisites)',
               existing_nullable=True)
    op.alter_column('wallets', 'tron_address',
               existing_type=sa.VARCHAR(length=34),
               comment='TRON address',
               existing_comment='TRON address (optional for external Ethereum-only requisites)',
               existing_nullable=True)
    op.alter_column('wallet_users', 'profile',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Space profile: description, icon (base64)',
               existing_comment='Space profile: description, company_name, icon (base64), optional language (ru|en)',
               existing_nullable=True)
    op.drop_index(op.f('ix_wallet_space_ui_prefs_id'), table_name='wallet_space_ui_prefs')
    op.drop_index(op.f('ix_token_balance_cache_id'), table_name='token_balance_cache')
    op.drop_index(op.f('ix_token_balance_cache_blockchain'), table_name='token_balance_cache')
    op.alter_column('token_balance_cache', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Time of last update (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('token_balance_cache', 'balance_raw',
               existing_type=sa.NUMERIC(precision=78, scale=0),
               comment=None,
               existing_comment='Token balance in base-units/raw uint256',
               existing_nullable=False)
    op.alter_column('token_balance_cache', 'contract_address',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Token contract address in native encoding for the chain',
               existing_nullable=False)
    op.alter_column('token_balance_cache', 'blockchain',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Chain identifier (e.g. TRON, ETH)',
               existing_nullable=False)
    op.alter_column('token_balance_cache', 'address',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Wallet address in native encoding for the chain (e.g. TRON base58)',
               existing_nullable=False)
    op.alter_column('token_balance_cache', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Autoincrement primary key',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_space_payment_form_overrides_space'), table_name='space_payment_form_overrides')
    op.drop_index(op.f('ix_space_payment_form_overrides_id'), table_name='space_payment_form_overrides')
    op.drop_index(op.f('ix_primary_wallets_wallet_user_id'), table_name='primary_wallets')
    op.create_index('ix_primary_wallets_wallet_user_id', 'primary_wallets', ['wallet_user_id'], unique=False)
    op.create_unique_constraint('primary_wallets_wallet_user_id_key', 'primary_wallets', ['wallet_user_id'])
    op.drop_index(op.f('ix_payment_request_uid'), table_name='payment_request')
    op.drop_index(op.f('ix_payment_request_public_ref'), table_name='payment_request')
    op.drop_index(op.f('ix_payment_request_pk'), table_name='payment_request')
    op.create_unique_constraint('uq_payment_request_uid', 'payment_request', ['uid'])
    op.create_index('uq_payment_request_public_ref', 'payment_request', ['public_ref'], unique=False)
    op.create_index('ix_payment_request_commissioners_gin', 'payment_request', ['commissioners'], unique=False, postgresql_using='gin')
    op.alter_column('payment_request', 'deactivated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Деактивация пользователем; NULL — активна',
               existing_comment='Деактивация владельцем; NULL — заявка активна в списке',
               existing_nullable=True)
    op.alter_column('payment_request', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Срок действия; NULL — без ограничения',
               existing_comment='Срок действия заявки; NULL — без ограничения по времени',
               existing_nullable=True)
    op.alter_column('payment_request', 'heading',
               existing_type=sa.VARCHAR(length=256),
               comment='Пользовательский заголовок заявки',
               existing_comment='Пользовательский заголовок (опционально)',
               existing_nullable=True)
    op.alter_column('payment_request', 'arbiter_did',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='DID арбитра (контекст Simple из path arbiter_space_did)',
               existing_nullable=False)
    op.alter_column('payment_request', 'space_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Primary space (WalletUser row)',
               existing_nullable=False)
    op.alter_column('payment_request', 'public_ref',
               existing_type=sa.VARCHAR(length=10),
               comment='Короткий публичный код заявки (список/ссылки)',
               existing_comment='Короткий публичный код заявки (ссылки, resolve)',
               existing_nullable=False)
    op.alter_column('orders', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='kind, diff, статусы multisig, адреса — гибко через JSON',
               existing_comment='kind, wallet_id (дубль id для UI), diff, multisig_setup_status, адреса',
               existing_nullable=True)
    op.alter_column('orders', 'space_wallet_id',
               existing_type=sa.INTEGER(),
               comment='Ramp-кошелёк спейса (связь с owner через wallets.owner_did)',
               existing_comment='Ramp-кошелёк спейса; связь с space через wallets.owner_did',
               existing_nullable=True)
    op.alter_column('orders', 'dedupe_key',
               existing_type=sa.VARCHAR(length=255),
               comment='Стабильный ключ для upsert refresh',
               existing_comment='Стабильный ключ для идемпотентного refresh',
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Идентификатор ордера',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_guarantor_profiles_id'), table_name='guarantor_profiles')
    op.alter_column('guarantor_profiles', 'arbiter_public_slug',
               existing_type=sa.VARCHAR(length=64),
               comment='Уникальный сегмент URL /arbiter/{slug} вместо DID',
               existing_comment='Уникальный сегмент URL /arbiter/{slug} вместо DID арбитра',
               existing_nullable=True)
    op.drop_index(op.f('ix_guarantor_directions_id'), table_name='guarantor_directions')
    op.alter_column('guarantor_directions', 'payment_code',
               existing_type=sa.VARCHAR(length=128),
               comment='Код платёжного метода (payment_code в bc.yaml)',
               existing_comment='Код платёжного метода (payment_code в bc.yaml). Зарезервировано: «*» — все способы оплаты для данной валюты; с конкретными методами по той же валюте в одном space не сочетается (проверка в GuarantorService).',
               existing_nullable=False)
    op.drop_index(op.f('ix_exchange_services_space'), table_name='exchange_services')
    op.drop_index(op.f('ix_exchange_services_payment_code'), table_name='exchange_services')
    op.alter_column('exchange_services', 'payment_code',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Код платёжного метода (bc.yaml); форма из резолвера если requisites_form_schema пуст',
               existing_nullable=True)
    op.alter_column('exchange_services', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Описание направления для UI',
               existing_nullable=True)
    op.alter_column('exchange_services', 'space_wallet_id',
               existing_type=sa.INTEGER(),
               comment='Корпоративный кошелёк спейса (wallets.id); обязателен для off_ramp',
               existing_comment='Корпоративный кошелёк спейса (реквизиты offRamp); NULL для on_ramp',
               existing_nullable=True)
    op.alter_column('exchange_services', 'space',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Идентификатор space (как в URL /{space}/…)',
               existing_nullable=False)
    op.drop_index('ix_deal_signers', table_name='deal', postgresql_using='gin')
    op.alter_column('deal', 'arbiter_did',
               existing_type=sa.VARCHAR(length=255),
               comment='Arbiter DID',
               existing_comment='Arbiter DID (space identifier, primary address may change)',
               existing_nullable=False)
    op.alter_column('deal', 'receiver_did',
               existing_type=sa.VARCHAR(length=255),
               comment='Receiver DID',
               existing_comment='Receiver DID (space identifier, primary address may change)',
               existing_nullable=False)
    op.alter_column('deal', 'sender_did',
               existing_type=sa.VARCHAR(length=255),
               comment='Sender DID (owner of the deal)',
               existing_comment='Sender DID (space identifier, primary address may change)',
               existing_nullable=False)
    op.drop_column('deal', 'signers')
    # ### end Alembic commands ###
