"""initial tables

Revision ID: 80fff5fb203c
Revises: 
Create Date: 2026-03-07 23:03:09.994533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80fff5fb203c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_tron_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tron_address', sa.String(length=34), nullable=False, comment='Whitelisted TRON address'),
    sa.Column('label', sa.String(length=255), nullable=True, comment='Optional label for this address'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this address is active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_tron_addresses_id'), 'admin_tron_addresses', ['id'], unique=False)
    op.create_index(op.f('ix_admin_tron_addresses_tron_address'), 'admin_tron_addresses', ['tron_address'], unique=True)
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True, comment='Admin username'),
    sa.Column('password_hash', sa.Text(), nullable=True, comment='Hashed password (bcrypt)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('advertisements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Autoincrement primary key'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='User ID from wallet_users table'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Display name for the advertisement'),
    sa.Column('description', sa.Text(), nullable=False, comment='Detailed description of the offer'),
    sa.Column('fee', sa.String(length=10), nullable=False, comment="Fee percentage (e.g. '2.5')"),
    sa.Column('min_limit', sa.Integer(), nullable=False, comment='Minimum transaction limit in USDT'),
    sa.Column('max_limit', sa.Integer(), nullable=False, comment='Maximum transaction limit in USDT'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='Currency code (USD, EUR, RUB, etc.)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the advertisement is active'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Whether the advertisement is verified by admin'),
    sa.Column('escrow_enabled', sa.Boolean(), nullable=False, comment='Whether escrow deals are enabled (agent conducts deal using their liquidity, debiting funds from escrow address upon service delivery)'),
    sa.Column('rating', sa.String(length=10), nullable=True, comment="User rating (e.g. '4.9')"),
    sa.Column('deals_count', sa.Integer(), nullable=False, comment='Number of completed deals'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_advertisements_currency_active', 'advertisements', ['currency', 'is_active'], unique=False)
    op.create_index(op.f('ix_advertisements_id'), 'advertisements', ['id'], unique=False)
    op.create_index('ix_advertisements_user_active', 'advertisements', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_advertisements_user_id'), 'advertisements', ['user_id'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Autoincrement primary key'),
    sa.Column('connection_id', sa.String(length=255), nullable=False, comment='Unique connection identifier (message ID)'),
    sa.Column('my_did', sa.String(length=255), nullable=False, comment='Our DID'),
    sa.Column('their_did', sa.String(length=255), nullable=True, comment='Their DID (null for pending invitations)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Connection status'),
    sa.Column('connection_type', sa.String(length=20), nullable=False, comment='Type of connection message'),
    sa.Column('label', sa.String(length=255), nullable=True, comment='Human-readable label'),
    sa.Column('connection_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional connection metadata'),
    sa.Column('message_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Original DIDComm message data'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('established_at', sa.DateTime(timezone=True), nullable=True, comment='When connection was established (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_connection_id'), 'connections', ['connection_id'], unique=True)
    op.create_index('ix_connections_connection_metadata', 'connections', ['connection_metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_index(op.f('ix_connections_my_did'), 'connections', ['my_did'], unique=False)
    op.create_index('ix_connections_my_did_status', 'connections', ['my_did', 'status'], unique=False)
    op.create_index(op.f('ix_connections_status'), 'connections', ['status'], unique=False)
    op.create_index(op.f('ix_connections_their_did'), 'connections', ['their_did'], unique=False)
    op.create_index('ix_connections_their_did_status', 'connections', ['their_did', 'status'], unique=False)
    op.create_table('escrow_operations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Autoincrement primary key'),
    sa.Column('blockchain', sa.String(length=50), nullable=False, comment='Blockchain name (tron, eth, etc.)'),
    sa.Column('network', sa.String(length=50), nullable=False, comment='Network name (mainnet, testnet, etc.)'),
    sa.Column('escrow_type', sa.String(length=20), nullable=False, comment='Escrow type (multisig, contract)'),
    sa.Column('escrow_address', sa.String(length=255), nullable=False, comment='Escrow address in blockchain'),
    sa.Column('owner_did', sa.String(length=255), nullable=False, comment='Owner DID - пользователь, которому принадлежит escrow'),
    sa.Column('participant1_address', sa.String(length=255), nullable=False, comment='First participant address'),
    sa.Column('participant2_address', sa.String(length=255), nullable=False, comment='Second participant address'),
    sa.Column('multisig_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='MultisigConfig configuration (JSONB)'),
    sa.Column('address_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Mapping of addresses to roles (participant, arbiter)'),
    sa.Column('arbiter_address', sa.String(length=255), nullable=True, comment='Arbiter address (can be changed by participants)'),
    sa.Column('encrypted_mnemonic', sa.Text(), nullable=True, comment='Encrypted mnemonic phrase for escrow (optional)'),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False, comment='Escrow status (pending, active, inactive)'),
    sa.Column('payout_executor_address', sa.String(length=255), nullable=True, comment='Адрес контракта PayoutAndFeesExecutor (TRON)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_escrow_multisig_config', 'escrow_operations', ['multisig_config'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_escrow_operations_blockchain'), 'escrow_operations', ['blockchain'], unique=False)
    op.create_index(op.f('ix_escrow_operations_id'), 'escrow_operations', ['id'], unique=False)
    op.create_index(op.f('ix_escrow_operations_network'), 'escrow_operations', ['network'], unique=False)
    op.create_index(op.f('ix_escrow_operations_owner_did'), 'escrow_operations', ['owner_did'], unique=False)
    op.create_index(op.f('ix_escrow_operations_participant1_address'), 'escrow_operations', ['participant1_address'], unique=False)
    op.create_index(op.f('ix_escrow_operations_participant2_address'), 'escrow_operations', ['participant2_address'], unique=False)
    op.create_index(op.f('ix_escrow_operations_status'), 'escrow_operations', ['status'], unique=False)
    op.create_index('ix_escrow_participants', 'escrow_operations', ['blockchain', 'network', 'participant1_address', 'participant2_address'], unique=False)
    op.create_index('uq_escrow_blockchain_network_address', 'escrow_operations', ['blockchain', 'network', 'escrow_address'], unique=True)
    op.create_table('node_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encrypted_mnemonic', sa.Text(), nullable=True, comment='Encrypted mnemonic phrase'),
    sa.Column('encrypted_pem', sa.Text(), nullable=True, comment='Encrypted PEM key data'),
    sa.Column('key_type', sa.String(length=20), nullable=False, comment='Type of key: mnemonic or pem'),
    sa.Column('ethereum_address', sa.String(length=42), nullable=True, comment='Ethereum address'),
    sa.Column('service_endpoint', sa.String(length=255), nullable=True, comment='Service endpoint URL for DIDComm'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this key is currently active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_settings_ethereum_address'), 'node_settings', ['ethereum_address'], unique=True)
    op.create_index(op.f('ix_node_settings_id'), 'node_settings', ['id'], unique=False)
    op.create_table('storage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Autoincrement primary key'),
    sa.Column('uuid', sa.UUID(), nullable=False, comment='UUID v1 identifier'),
    sa.Column('space', sa.String(length=255), nullable=False, comment='Space identifier for organizing data'),
    sa.Column('schema_ver', sa.String(length=10), server_default='1', nullable=False, comment='Schema version'),
    sa.Column('deal_uid', sa.String(length=255), nullable=True, comment='Deal UID (base58 UUID) reference'),
    sa.Column('owner_did', sa.String(length=255), nullable=True, comment='Owner DID - пользователь, которому принадлежит ledger'),
    sa.Column('conversation_id', sa.String(length=255), nullable=True, comment='Conversation ID для группировки сообщений'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON payload data'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_conversation_id'), 'storage', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_storage_deal_uid'), 'storage', ['deal_uid'], unique=False)
    op.create_index(op.f('ix_storage_id'), 'storage', ['id'], unique=False)
    op.create_index(op.f('ix_storage_owner_did'), 'storage', ['owner_did'], unique=False)
    op.create_index('ix_storage_payload', 'storage', ['payload'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_storage_space'), 'storage', ['space'], unique=False)
    op.create_index(op.f('ix_storage_uuid'), 'storage', ['uuid'], unique=True)
    op.create_table('wallet_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=255), nullable=False, comment='Wallet address (TRON: 34 chars, ETH: 42 chars)'),
    sa.Column('blockchain', sa.String(length=20), nullable=False, comment='Blockchain type: tron, ethereum, bitcoin, etc.'),
    sa.Column('did', sa.String(length=300), nullable=False, comment='Decentralized Identifier (DID)'),
    sa.Column('nickname', sa.String(length=100), nullable=False, comment='User display name (unique)'),
    sa.Column('avatar', sa.Text(), nullable=True, comment='User avatar in base64 format (data:image/...)'),
    sa.Column('access_to_admin_panel', sa.Boolean(), nullable=False, comment='Access to admin panel'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Whether the user is verified (document verification)'),
    sa.Column('balance_usdt', sa.Numeric(precision=20, scale=8), nullable=False, comment='USDT balance'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_users_blockchain'), 'wallet_users', ['blockchain'], unique=False)
    op.create_index(op.f('ix_wallet_users_did'), 'wallet_users', ['did'], unique=True)
    op.create_index(op.f('ix_wallet_users_id'), 'wallet_users', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_users_nickname'), 'wallet_users', ['nickname'], unique=True)
    op.create_index(op.f('ix_wallet_users_wallet_address'), 'wallet_users', ['wallet_address'], unique=True)
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Wallet name (editable)'),
    sa.Column('encrypted_mnemonic', sa.Text(), nullable=False, comment='Encrypted mnemonic phrase'),
    sa.Column('tron_address', sa.String(length=34), nullable=False, comment='TRON address'),
    sa.Column('ethereum_address', sa.String(length=42), nullable=False, comment='Ethereum address'),
    sa.Column('account_permissions', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='TRON account permissions from blockchain'),
    sa.Column('role', sa.String(length=255), nullable=True, comment='Wallet role'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ethereum_address', 'role', name='uq_wallets_ethereum_address_role'),
    sa.UniqueConstraint('tron_address', 'role', name='uq_wallets_tron_address_role')
    )
    op.create_index('ix_wallets_ethereum_address', 'wallets', ['ethereum_address'], unique=False)
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_index('ix_wallets_role', 'wallets', ['role'], unique=False)
    op.create_index('ix_wallets_tron_address', 'wallets', ['tron_address'], unique=False)
    op.create_table('billing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_user_id', sa.Integer(), nullable=False, comment='Reference to wallet user'),
    sa.Column('usdt_amount', sa.Numeric(precision=20, scale=8), nullable=False, comment='USDT amount: positive for deposit, negative for withdrawal'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Transaction timestamp'),
    sa.ForeignKeyConstraint(['wallet_user_id'], ['wallet_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_created_at'), 'billing', ['created_at'], unique=False)
    op.create_index(op.f('ix_billing_id'), 'billing', ['id'], unique=False)
    op.create_index(op.f('ix_billing_wallet_user_id'), 'billing', ['wallet_user_id'], unique=False)
    op.create_table('deal',
    sa.Column('pk', sa.BigInteger(), autoincrement=True, nullable=False, comment='Autoincrement primary key'),
    sa.Column('uid', sa.String(length=255), nullable=False, comment='Base58 UUID identifier (primary identifier)'),
    sa.Column('sender_did', sa.String(length=255), nullable=False, comment='Sender DID (owner of the deal)'),
    sa.Column('receiver_did', sa.String(length=255), nullable=False, comment='Receiver DID'),
    sa.Column('arbiter_did', sa.String(length=255), nullable=False, comment='Arbiter DID'),
    sa.Column('escrow_id', sa.BigInteger(), nullable=True, comment='Reference to escrow operation'),
    sa.Column('label', sa.Text(), nullable=False, comment='Text description of the deal'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание сделки (дополнительное описание, отдельно от label)'),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=True, comment='Сумма сделки'),
    sa.Column('commissioners', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Комиссионеры: массив {address, amount} для атомарной выплаты (основа + комиссии)'),
    sa.Column('requisites', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Текущие реквизиты сделки (ФИО, назначение, валюта и др.)'),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Ссылки на файлы в Storage (массив объектов с uuid, name, type и др.)'),
    sa.Column('need_receiver_approve', sa.Boolean(), server_default='false', nullable=False, comment='Требуется ли одобрение получателя'),
    sa.Column('status', sa.String(length=50), server_default='wait_deposit', nullable=False, comment='Статус сделки: wait_deposit, processing, success, appeal, wait_arbiter, recline_appeal, resolving_sender, resolving_receiver, resolved_sender, resolved_receiver'),
    sa.Column('payout_txn', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Оффлайн-транзакция выплаты по сделке (зависит от status); null при appeal или без эскроу'),
    sa.Column('deposit_txn_hash', sa.String(length=66), nullable=True, comment='Hash транзакции депозита в эскроу'),
    sa.Column('payout_txn_hash', sa.String(length=66), nullable=True, comment='Hash подтверждённой транзакции выплаты'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrow_operations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index('ix_deal_arbiter_did', 'deal', ['arbiter_did'], unique=False)
    op.create_index('ix_deal_attachments', 'deal', ['attachments'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_deal_deposit_txn_hash'), 'deal', ['deposit_txn_hash'], unique=False)
    op.create_index('ix_deal_escrow_id', 'deal', ['escrow_id'], unique=False)
    op.create_index(op.f('ix_deal_payout_txn_hash'), 'deal', ['payout_txn_hash'], unique=False)
    op.create_index(op.f('ix_deal_pk'), 'deal', ['pk'], unique=False)
    op.create_index('ix_deal_receiver_did', 'deal', ['receiver_did'], unique=False)
    op.create_index('ix_deal_requisites', 'deal', ['requisites'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_deal_sender_did'), 'deal', ['sender_did'], unique=False)
    op.create_index('ix_deal_status', 'deal', ['status'], unique=False)
    op.create_index(op.f('ix_deal_uid'), 'deal', ['uid'], unique=True)
    op.create_table('escrow_txn',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Autoincrement primary key'),
    sa.Column('escrow_id', sa.BigInteger(), nullable=False, comment='Reference to escrow operation (one-to-one)'),
    sa.Column('txn', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Transaction or event data (JSONB)'),
    sa.Column('type', sa.String(length=20), nullable=False, comment="Type: 'txn' for transaction, 'event' for event"),
    sa.Column('comment', sa.Text(), nullable=False, comment='Comment describing the transaction or event'),
    sa.Column('counter', sa.Integer(), server_default='1', nullable=False, comment='Counter for duplicate events (incremented when same event occurs)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrow_operations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_escrow_txn_data', 'escrow_txn', ['txn'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_escrow_txn_escrow_id'), 'escrow_txn', ['escrow_id'], unique=True)
    op.create_index(op.f('ix_escrow_txn_id'), 'escrow_txn', ['id'], unique=False)
    op.create_index('ix_escrow_txn_type', 'escrow_txn', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_escrow_txn_type', table_name='escrow_txn')
    op.drop_index(op.f('ix_escrow_txn_id'), table_name='escrow_txn')
    op.drop_index(op.f('ix_escrow_txn_escrow_id'), table_name='escrow_txn')
    op.drop_index('ix_escrow_txn_data', table_name='escrow_txn', postgresql_using='gin')
    op.drop_table('escrow_txn')
    op.drop_index(op.f('ix_deal_uid'), table_name='deal')
    op.drop_index('ix_deal_status', table_name='deal')
    op.drop_index(op.f('ix_deal_sender_did'), table_name='deal')
    op.drop_index('ix_deal_requisites', table_name='deal', postgresql_using='gin')
    op.drop_index('ix_deal_receiver_did', table_name='deal')
    op.drop_index(op.f('ix_deal_pk'), table_name='deal')
    op.drop_index(op.f('ix_deal_payout_txn_hash'), table_name='deal')
    op.drop_index('ix_deal_escrow_id', table_name='deal')
    op.drop_index(op.f('ix_deal_deposit_txn_hash'), table_name='deal')
    op.drop_index('ix_deal_attachments', table_name='deal', postgresql_using='gin')
    op.drop_index('ix_deal_arbiter_did', table_name='deal')
    op.drop_table('deal')
    op.drop_index(op.f('ix_billing_wallet_user_id'), table_name='billing')
    op.drop_index(op.f('ix_billing_id'), table_name='billing')
    op.drop_index(op.f('ix_billing_created_at'), table_name='billing')
    op.drop_table('billing')
    op.drop_index('ix_wallets_tron_address', table_name='wallets')
    op.drop_index('ix_wallets_role', table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_index('ix_wallets_ethereum_address', table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_wallet_users_wallet_address'), table_name='wallet_users')
    op.drop_index(op.f('ix_wallet_users_nickname'), table_name='wallet_users')
    op.drop_index(op.f('ix_wallet_users_id'), table_name='wallet_users')
    op.drop_index(op.f('ix_wallet_users_did'), table_name='wallet_users')
    op.drop_index(op.f('ix_wallet_users_blockchain'), table_name='wallet_users')
    op.drop_table('wallet_users')
    op.drop_index(op.f('ix_storage_uuid'), table_name='storage')
    op.drop_index(op.f('ix_storage_space'), table_name='storage')
    op.drop_index('ix_storage_payload', table_name='storage', postgresql_using='gin')
    op.drop_index(op.f('ix_storage_owner_did'), table_name='storage')
    op.drop_index(op.f('ix_storage_id'), table_name='storage')
    op.drop_index(op.f('ix_storage_deal_uid'), table_name='storage')
    op.drop_index(op.f('ix_storage_conversation_id'), table_name='storage')
    op.drop_table('storage')
    op.drop_index(op.f('ix_node_settings_id'), table_name='node_settings')
    op.drop_index(op.f('ix_node_settings_ethereum_address'), table_name='node_settings')
    op.drop_table('node_settings')
    op.drop_index('uq_escrow_blockchain_network_address', table_name='escrow_operations')
    op.drop_index('ix_escrow_participants', table_name='escrow_operations')
    op.drop_index(op.f('ix_escrow_operations_status'), table_name='escrow_operations')
    op.drop_index(op.f('ix_escrow_operations_participant2_address'), table_name='escrow_operations')
    op.drop_index(op.f('ix_escrow_operations_participant1_address'), table_name='escrow_operations')
    op.drop_index(op.f('ix_escrow_operations_owner_did'), table_name='escrow_operations')
    op.drop_index(op.f('ix_escrow_operations_network'), table_name='escrow_operations')
    op.drop_index(op.f('ix_escrow_operations_id'), table_name='escrow_operations')
    op.drop_index(op.f('ix_escrow_operations_blockchain'), table_name='escrow_operations')
    op.drop_index('ix_escrow_multisig_config', table_name='escrow_operations', postgresql_using='gin')
    op.drop_table('escrow_operations')
    op.drop_index('ix_connections_their_did_status', table_name='connections')
    op.drop_index(op.f('ix_connections_their_did'), table_name='connections')
    op.drop_index(op.f('ix_connections_status'), table_name='connections')
    op.drop_index('ix_connections_my_did_status', table_name='connections')
    op.drop_index(op.f('ix_connections_my_did'), table_name='connections')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_index('ix_connections_connection_metadata', table_name='connections', postgresql_using='gin')
    op.drop_index(op.f('ix_connections_connection_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_advertisements_user_id'), table_name='advertisements')
    op.drop_index('ix_advertisements_user_active', table_name='advertisements')
    op.drop_index(op.f('ix_advertisements_id'), table_name='advertisements')
    op.drop_index('ix_advertisements_currency_active', table_name='advertisements')
    op.drop_table('advertisements')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index(op.f('ix_admin_tron_addresses_tron_address'), table_name='admin_tron_addresses')
    op.drop_index(op.f('ix_admin_tron_addresses_id'), table_name='admin_tron_addresses')
    op.drop_table('admin_tron_addresses')
    # ### end Alembic commands ###
